// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// test
Rcpp::List test(arma::mat data);
RcppExport SEXP _abcpp_test(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(test(data));
    return rcpp_result_gen;
END_RCPP
}
// runAbcMCMC_univ_R
Rcpp::List runAbcMCMC_univ_R(Rcpp::NumericVector data, int nrep, double theta, double sigma, double m0, double k0, double a0, double b0, double eps, int p, std::string dist);
RcppExport SEXP _abcpp_runAbcMCMC_univ_R(SEXP dataSEXP, SEXP nrepSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP m0SEXP, SEXP k0SEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP epsSEXP, SEXP pSEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< double >::type k0(k0SEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< std::string >::type dist(distSEXP);
    rcpp_result_gen = Rcpp::wrap(runAbcMCMC_univ_R(data, nrep, theta, sigma, m0, k0, a0, b0, eps, p, dist));
    return rcpp_result_gen;
END_RCPP
}
// runAbcMCMC_graph
Rcpp::List runAbcMCMC_graph(std::vector<arma::mat> data, int nrep, double theta, double sigma, arma::vec m0, arma::mat var_chol, const std::vector<arma::vec>& inits, double eps, std::string dist);
RcppExport SEXP _abcpp_runAbcMCMC_graph(SEXP dataSEXP, SEXP nrepSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP m0SEXP, SEXP var_cholSEXP, SEXP initsSEXP, SEXP epsSEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<arma::mat> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type var_chol(var_cholSEXP);
    Rcpp::traits::input_parameter< const std::vector<arma::vec>& >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< std::string >::type dist(distSEXP);
    rcpp_result_gen = Rcpp::wrap(runAbcMCMC_graph(data, nrep, theta, sigma, m0, var_chol, inits, eps, dist));
    return rcpp_result_gen;
END_RCPP
}
// graph_dist_R
double graph_dist_R(const arma::mat& g1, const arma::mat& g2);
RcppExport SEXP _abcpp_graph_dist_R(SEXP g1SEXP, SEXP g2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type g2(g2SEXP);
    rcpp_result_gen = Rcpp::wrap(graph_dist_R(g1, g2));
    return rcpp_result_gen;
END_RCPP
}
// simulate_graph
arma::mat simulate_graph(const arma::vec& theta);
RcppExport SEXP _abcpp_simulate_graph(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_graph(theta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_abcpp_test", (DL_FUNC) &_abcpp_test, 1},
    {"_abcpp_runAbcMCMC_univ_R", (DL_FUNC) &_abcpp_runAbcMCMC_univ_R, 11},
    {"_abcpp_runAbcMCMC_graph", (DL_FUNC) &_abcpp_runAbcMCMC_graph, 9},
    {"_abcpp_graph_dist_R", (DL_FUNC) &_abcpp_graph_dist_R, 2},
    {"_abcpp_simulate_graph", (DL_FUNC) &_abcpp_simulate_graph, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_abcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
